import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { AuthProvider } from "@/components/AuthProvider";
import { Toaster } from "sonner";
import MixpanelProvider from "@/components/MixpanelProvider";
// import MixpanelProvider from "@/components/MixpanelProvider"; // We'll create this component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SkillUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* ✅ Razorpay Script */}
          <Script 
            src="https://checkout.razorpay.com/v1/checkout.js" 
            strategy="beforeInteractive"
          />
          
          {/* ✅ Mixpanel Integration */}
          <MixpanelProvider>
            {children}
          </MixpanelProvider>

          <Toaster richColors/>
        </body>
      </html>
    </AuthProvider>
  );
}
